# Generated by Django 3.1.7 on 2021-03-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_exam_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='jobs',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
